library(dplyr)


#' @export
#' @title nucleotide diversity by site
#' @param nucdivSpecies a data.frame of nucleotide diversity by species
#' generated by `species_nucleotide_diversity` function.
#' @return a data.frame of nucleotide diversity by site
nucleotide_diversity_sites <- function(nucdivSpecies) {
  nucdivSites <- nucdivSpecies %>% dplyr::group_by(site.ids) %>%
    dplyr::mutate(nucDiv=replace(nucDiv, nucDiv==0, 0.00001)) %>%
    dplyr::summarize(nucDivMean = mean(nucDiv, na.rm=TRUE)) %>%
    dplyr::mutate(site.ids.grid=paste("ID",site.ids,sep=""))
  return(nucdivSites)
}






